name: Update

on:
  push:
    branches:
      - master
    paths-ignore:
      - "dist/**"

  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

permissions: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          token: "${{ secrets.BOT_GITHUB_TOKEN }}"

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - run: go run ./

      - run: git pull

      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: 🔄 Update
          commit_author: StarryBlueSky-bot <97773209+StarryBlueSky-bot@users.noreply.github.com>
